# Generated by Django 5.1.1 on 2024-09-09 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga_module', '0002_subject_subject_day_subject_subject_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(max_length=255)),
                ('room_locale', models.CharField(choices=[('CB', 'Main'), ('CBS', 'South'), ('CBE', 'East')], default='CB', max_length=3)),
                ('room_type', models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], default='LEC', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_id', models.IntegerField()),
                ('teacher_name', models.CharField(max_length=255)),
                ('subject_code1', models.CharField(max_length=255)),
                ('subject_code2', models.CharField(max_length=255)),
                ('subject_code3', models.CharField(max_length=255)),
            ],
        ),
    ]
