# Generated by Django 5.1.1 on 2024-09-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ga_module', '0003_room_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_locale',
            field=models.CharField(choices=[('CB', 'Main'), ('CBS', 'South'), ('CBE', 'East')], default='CB', max_length=64),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('LEC', 'Lecture'), ('LAB', 'Laboratory')], default='LEC', max_length=64),
        ),
    ]
